version: '3.8'

volumes:
  asukaapi:
  asukaapi-mysql:

services:
  asukaapi:
    container_name: asukaapi
    image: asukaapi
    restart: always
    # To store logs.
    volumes:
      - asukaapi:/asukaapi
    env_file:
      - .env
    ports:
      - 5100:5100
      - 5101:5101
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    # Application might continue crashing until
    # dependent service(s) fully initialize.
    depends_on:
      - db

  db:
    container_name: db
    image: mysql
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - asukaapi-mysql:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
