version: '3.8'

volumes:
  asukaapi:
  asukaapi-db:

services:
  asukaapi:
    container_name: asukaapi
    image: asukaapi
    restart: always
    # To store logs.
    volumes:
      - asukaapi:/asukaapi
    env_file:
      - .env
    ports:
      - 5100:5100
      - 5101:5101
    build:
      context: .
      dockerfile: Dockerfile
    # Application might continue crashing until
    # dependent service(s) fully initialize.
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    restart: always
    volumes:
      - asukaapi-db:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
