version: '3.8'

volumes:
  asukaapi:
  mysql-db-data:

services:
  asukaapi:
    container_name: asukaapi
    image: asukaapi
    restart: always
    volumes:
      - asukaapi:/asukaapi
    env_file:
      - .env
    ports:
      - 5000:5000
      - 5001:5001
    build:
      context: .
      dockerfile: src/WebApi/Dockerfile
    # Application might continue crashing until
    # dependent service(s) fully initialize
    depends_on:
      - db

  db:
    container_name: db
    image: mysql
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql-db-data:/var/lib/mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306

  flyway:
    container_name: flyway
    image: flyway/flyway
    command: -url=jdbc:mysql://db -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    env_file:
      - .env
    environment:
      FLYWAY_EDITION: ${FLYWAY_EDITION}
      FLYWAY_USER: ${DB_USERNAME}
      FLYWAY_PASSWORD: ${DB_PASSWORD}
      FLYWAY_SCHEMAS: ${DB_SCHEMA}
    depends_on:
      - db
